### ISSUE TITLE
What can be ported from https://solanaceaesource.myspecies.info/

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-solanaceae#1]
Hi @SandyKnapp
This is probably the most natural place to leave tasks for the project. 

I just looked at https://solanaceaesource.myspecies.info/
Most of the pages look like they could be ported fairly easily (at first glance at least). Though it might require some tedious work.

The `pbi project` tab could perhaps be done with the documentation sidebar layout https://hp-theme.gbif-staging.org/layout/documentation
Similar for `what are nightshades`

The `solanaceae` would be the Checklist bank widgets

`Specimens` would be the occurrence search I suppose?

`Media gallery` and `literature` we do not really have a match for I believe.

It could probably be created, but it requires developer work (or unfeasible amounts of manual curation)

Let me know if there is anything I can help with.

**Comment by SandyKnapp** [comment]
Hi Morten,

I have selected some photos....  How best to send them? And what metadata do I need to have with them - can I do this with GitHub? I will need some time to learn how to do this!!

Sandy

Dr Sandra Knapp, botanist (she/her)
+44 (0) 20 7942 5171
Natural History Museum
Cromwell Road
London SW7 5BD
 ***@***.***
Solanaceae Source http://www.solanaceaesource.org<http://www.solanaceaesource.org/>
Flora Mesoamericana http://www.mobot.org/fm

**Comment by MortenHofft** [comment]
You should upload your photos to the /assets folder. High resolution

That is all that you HAVE to do.
Then you can choose to add a data file that list all the images. That will make it a bit easier to reuse them. I've created an example https://github.com/gbif/hp-solanaceae/blob/master/_data/images.yml
And used it here https://github.com/gbif/hp-solanaceae/blob/master/home.md

**Comment by SandyKnapp** [comment]
OK – I can do that I think – I will try this afternoon – this is a steep learning curve for me 😊

Dr Sandra Knapp, botanist (she/her)
+44 (0) 20 7942 5171
Natural History Museum
Cromwell Road
London SW7 5BD
 ***@***.***
Solanaceae Source http://www.solanaceaesource.org<http://www.solanaceaesource.org/>
Flora Mesoamericana http://www.mobot.org/fm
